###
POST http://localhost:8000/students/login
Content-Type: application/json

{
    "email": "student@student.com",
    "password": "student"

}
###
GET http://localhost:8000/students/

###
POST http://localhost:8000/students/
Content-Type: application/json

{
    "first": "Coty",
    "last": "Auger",
    "email": "Coty_Auger18@yahoo.com",
    "pass": "student",
    "verifyCode": "abc123"
}