# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - blueocean

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push container image to registry
      uses: docker/compose-action@1.3.2
      with:
        compose-file: ./docker-compose.yml
        context: .
        command: build
        services: career-services-hub-20
        push-registry: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_b81e884640314884a3c3e8eb98fc65d3 }}
        push-tag: ${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'blueocean'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f548754d2ff146db8e06a8a8bf6ea775 }}
        images: 'ghcr.io/gschool-blue-ocean/gschool-blue-ocean/gschool-blue-ocean/career-services-hub-20-${{ github.sha }}'




